export * from "./city.interface.js";
export * from "./comment.interface.js";
export * from "./fileUpload.interface.js";
export * from "./geocode.interface.js";
export * from "./participants.interface.js";
export * from "./review.interface.js";
export * from "./timeSlot.interface.js";
export * from "./training.interface.js";
export * from "./user.interface.js";
